apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: mern
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: mern
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
