name: Deploy MERN App to AWS

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Set environment variables for Vite
      - name: Set Vite Environment Variables
        run: |
          echo "VITE_API_URL=http://${{ secrets.EC2_HOST }}:32000" >> devops_frontend/.env  # Change port if needed

      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Install and Build Frontend
      - name: Install & Build Frontend
        run: |
          cd devops_frontend
          npm install
          npm run build
          ls dist
          pwd
          ls -l
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          cat private-key.pem
          echo "Private Key File Exists $(test -f private-key.pem && echo 'Yes' || echo 'No')"
          echo "Current Working Directory:"
          pwd
          echo "Listing files:"
          ls -l
          scp -i private-key.pem -r dist ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/
          rm -f private-key.pem

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd devops_backend
          npm install

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build & Push Docker Images
      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend ./devops_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 & Deploy Backend on Kubernetes
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Ensure kubectl and Docker are installed
            which kubectl || sudo apt-get install -y kubectl
            which docker || sudo apt-get install -y docker.io

            # Save Kubernetes configurations on EC2
            echo "${{ secrets.K8S_BACKEND_DEPLOYMENT }}" > backend-deployment.yml

            # Apply Kubernetes configurations
            kubectl apply -f backend-deployment.yml
