name: Deploy MERN App to AWS

on:
  push:
    branches:
      - master  # Trigger on push to master branch (or the branch of your choice)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install and Build Frontend
      - name: Install & Build Frontend
        run: |
          cd devops_frontend
          npm install
          npm run build
          ls dist
          pwd
          ls -l
        # Write the private key from GitHub Secrets to a file
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private-key.pem

          # Set the correct file permissions for the private key
          chmod 600 private-key.pem

          # Check if the private key was written correctly (debug step)
          cat private-key.pem
          echo "Private Key File Exists: $(test -f private-key.pem && echo 'Yes' || echo 'No')"
          echo "Current Working Directory:"
          pwd
          echo "Listing files:"
          ls -l

          # Run SCP to copy the frontend files to EC2
          scp -i private-key.pem -r dist ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/

          # Clean up the private key file after use for security
          rm -f private-key.pem

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd devops_backend
          npm install

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build & Push Docker Images (Frontend & Backend)
      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend ./devops_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Copy Frontend to EC2
        # run: |
          # pwd
          # ls -l
          # echo "${{ secrets.EC2_PRIVATE_KEY }}" > private-key.pem
        
          #   # Set the correct permissions for the private key file
          # chmod 600 private-key.pem
        
          #   # Run SCP command
          # # scp -i private-key.pem -r devops_frontend/dist ec2-user@${{ secrets.EC2_HOST }}:/var/www/html/
        
          #   # Clean up the temporary private key file
          # rm -f private-key.pem
            
      - name: SSH into EC2 & Deploy Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop and remove existing backend container
            docker stop mern-backend || true
            docker rm mern-backend || true

            # Pull the latest backend image
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend

            # Run the backend
            docker run -d -p 5000:5000 --name mern-backend \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              ${{ secrets.DOCKER_USERNAME }}/mern-backend

            # Restart Nginx to serve the new frontend
            sudo systemctl restart nginx
