name: Deploy MERN App to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install and Build Frontend
      - name: Install & Build Frontend
        run: |
          cd frontend  # Ensure correct folder name
          npm install
          npm run build

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build & Push Docker Images (Frontend & Backend)
      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest ./devops_frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest ./devops_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop and remove existing containers
            docker stop mern-frontend mern-backend || true
            docker rm mern-frontend mern-backend || true

            # Pull latest images
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

            # Run backend with volume for persistent data
            docker run -d -p 5000:5000 --name mern-backend \
              -v backend_data:/app/uploads \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

            # Run frontend with Nginx serving Vite build
            docker run -d -p 80:80 --name mern-frontend \
              ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

            # Cleanup unused Docker images
            docker image prune -f
